"use client";

import { useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookMarked, Check, MessageSquareWarning, Plus, RefreshCw, ScanSearch, Trash2, X } from "lucide-react";
import { useParams } from "next/navigation";
import { useForm, useWatch } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { PageHeader } from "@/components/layout/page-header";
import { EmptyState } from "@/components/data-display/empty-state";
import { QueryState } from "@/components/data-display/query-state";
import { StatusBadge } from "@/components/data-display/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { controlApi, records, textValue, type JsonRecord } from "@/lib/api/control-plane";
import { decodeRouteParam } from "@/lib/routing";

const schema = z.object({ text: z.string().trim().min(4).max(20000), certainty: z.enum(["low", "medium", "high"]), note: z.string().trim().max(1000) });

function CreateKnowledgeDialog({ kbId }: { kbId: string }) {
  const [open, setOpen] = useState(false);
  const queryClient = useQueryClient();
  const form = useForm<z.infer<typeof schema>>({ resolver: zodResolver(schema), defaultValues: { text: "", certainty: "medium", note: "" } });
  const certainty = useWatch({ control: form.control, name: "certainty" });
  const mutation = useMutation({ mutationFn: (values: z.infer<typeof schema>) => controlApi.createKnowledge({ kb_id: kbId, text: values.text, certainty: values.certainty, source_note: values.note, origin: "manual_entry", related_chunk_ids: [] }), onSuccess: async () => { toast.success("派生知识已创建并进入审核"); setOpen(false); form.reset(); await queryClient.invalidateQueries({ queryKey: ["derived"] }); }, onError: (error) => form.setError("root", { message: error.message }) });
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="primary"><Plus className="size-4" />新增知识</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>新增派生知识</DialogTitle><DialogDescription>补充内容会进入现有审核与索引流程，不会绕过证据治理。</DialogDescription></DialogHeader><form onSubmit={form.handleSubmit((values) => mutation.mutate(values))}><div className="space-y-4"><div className="space-y-1.5"><Label htmlFor="knowledge-text">知识内容</Label><Textarea id="knowledge-text" className="min-h-36" {...form.register("text")} />{form.formState.errors.text ? <p className="text-xs text-error">{form.formState.errors.text.message}</p> : null}</div><div className="space-y-1.5"><Label>确定性</Label><Select value={certainty} onValueChange={(value) => form.setValue("certainty", value as z.infer<typeof schema>["certainty"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["low", "medium", "high"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label htmlFor="source-note">来源说明</Label><Textarea id="source-note" {...form.register("note")} /></div>{form.formState.errors.root ? <p className="text-xs text-error">{form.formState.errors.root.message}</p> : null}</div><DialogFooter><Button type="button" variant="ghost" onClick={() => setOpen(false)}>取消</Button><Button type="submit" variant="primary" loading={mutation.isPending}>保存为待审核</Button></DialogFooter></form></DialogContent></Dialog>;
}

export default function DerivedKnowledgePage() {
  const params = useParams<{ kbId: string }>();
  const kbId = decodeRouteParam(params.kbId);
  const queryClient = useQueryClient();
  const [status, setStatus] = useState("all");
  const knowledge = useQuery({ queryKey: ["derived", "knowledge", kbId, status], queryFn: () => controlApi.knowledge(kbId, status === "all" ? undefined : status) });
  const feedback = useQuery({ queryKey: ["derived", "feedback", kbId], queryFn: () => controlApi.feedback(kbId) });
  const analysis = useQuery({ queryKey: ["derived", "analysis", kbId], queryFn: () => controlApi.feedbackAnalysis(kbId) });
  const retrieval = useQuery({ queryKey: ["derived", "retrieval-feedback", kbId], queryFn: () => controlApi.retrievalFeedback(kbId) });
  const metrics = useQuery({ queryKey: ["derived", "metrics", kbId], queryFn: () => controlApi.feedbackLoopMetrics(kbId), retry: false });
  const knowledgeRows = records(knowledge.data, ["items", "knowledge", "entries"]);
  const feedbackRows = records(feedback.data, ["items", "feedback"]);
  const analysisRows = records(analysis.data, ["items", "analysis"]);
  const retrievalRows = records(retrieval.data, ["items", "feedback"]);
  const review = useMutation({ mutationFn: ({ row, action }: { row: JsonRecord; action: string }) => controlApi.reviewKnowledge(textValue(row.knowledge_id, textValue(row.id, "")), action), onSuccess: async (_, values) => { toast.success(values.action === "approve" ? "派生知识已通过" : "派生知识已拒绝"); await queryClient.invalidateQueries({ queryKey: ["derived"] }); }, onError: (error) => toast.error(error.message) });
  const remove = useMutation({ mutationFn: (row: JsonRecord) => controlApi.deleteKnowledge(textValue(row.knowledge_id, textValue(row.id, ""))), onSuccess: async () => { toast.success("派生知识已删除"); await queryClient.invalidateQueries({ queryKey: ["derived"] }); }, onError: (error) => toast.error(error.message) });
  const scan = useMutation({ mutationFn: () => controlApi.scanStaleKnowledge(kbId), onSuccess: async () => { toast.success("过期扫描已完成"); await queryClient.invalidateQueries({ queryKey: ["derived"] }); }, onError: (error) => toast.error(error.message) });
  const metricRow = metrics.data && typeof metrics.data === "object" && !Array.isArray(metrics.data) ? metrics.data as JsonRecord : {};
  return <div className="min-h-full"><PageHeader eyebrow="Knowledge governance" title="派生知识" description="管理人工补充、反馈纠错、冲突审核、过期检测和检索调权反馈。" actions={<><Button onClick={() => scan.mutate()} loading={scan.isPending}><ScanSearch className="size-4" />扫描过期</Button><CreateKnowledgeDialog kbId={kbId} /></>} /><div className="p-4 md:p-6"><div className="mb-5 grid gap-px overflow-hidden border border-border bg-border sm:grid-cols-4">{[["待审核", textValue(metricRow.pending_count, "—")], ["已通过", textValue(metricRow.approved_count, "—")], ["需更新", textValue(metricRow.stale_count, "—")], ["反馈总数", textValue(metricRow.feedback_count, String(feedbackRows.length))]].map(([label, value]) => <div key={label} className="bg-surface px-4 py-3"><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>)}</div><Tabs defaultValue="knowledge"><TabsList className="mb-4"><TabsTrigger value="knowledge">知识目录 <Badge className="ml-1">{knowledgeRows.length}</Badge></TabsTrigger><TabsTrigger value="feedback">用户反馈 <Badge className="ml-1">{feedbackRows.length}</Badge></TabsTrigger><TabsTrigger value="analysis">反馈理解 <Badge className="ml-1">{analysisRows.length}</Badge></TabsTrigger><TabsTrigger value="retrieval">检索调权 <Badge className="ml-1">{retrievalRows.length}</Badge></TabsTrigger></TabsList>
    <TabsContent value="knowledge"><section className="overflow-hidden border border-border bg-surface"><div className="flex h-11 items-center gap-3 border-b border-border px-4"><Label>状态</Label><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent>{["all", "pending", "approved", "rejected", "stale"].map((value) => <SelectItem key={value} value={value}>{value === "all" ? "全部" : value}</SelectItem>)}</SelectContent></Select><Button variant="ghost" size="icon" className="ml-auto" onClick={() => void knowledge.refetch()}><RefreshCw className="size-4" /></Button></div><QueryState pending={knowledge.isPending} error={knowledge.error} onRetry={() => void knowledge.refetch()} />{knowledge.data && !knowledgeRows.length ? <EmptyState icon={BookMarked} compact title="没有派生知识" description="新增人工知识，或从反馈纠错中保存内容。" action={<CreateKnowledgeDialog kbId={kbId} />} /> : <div className="divide-y divide-border">{knowledgeRows.map((row) => { const id = textValue(row.knowledge_id, textValue(row.id)); const rowStatus = textValue(row.status, "pending"); return <div key={id} className="grid grid-cols-[minmax(0,1fr)_100px_110px_auto] items-start gap-4 px-4 py-3"><div className="min-w-0"><p className="whitespace-pre-wrap text-[13px] leading-5">{textValue(row.text)}</p><p className="mt-1 truncate font-mono text-[10px] text-muted-foreground">{id} · {textValue(row.origin, "manual")}</p></div><StatusBadge status={rowStatus} /><Badge>{textValue(row.certainty, "medium")}</Badge><div className="flex gap-1">{["pending", "stale"].includes(rowStatus) ? <><Button variant="ghost" size="icon" className="text-success" onClick={() => review.mutate({ row, action: "approve" })} aria-label="通过"><Check className="size-4" /></Button><Button variant="ghost" size="icon" className="text-error" onClick={() => review.mutate({ row, action: "reject" })} aria-label="拒绝"><X className="size-4" /></Button></> : null}<Button variant="ghost" size="icon" className="text-error" onClick={() => remove.mutate(row)} aria-label="删除"><Trash2 className="size-4" /></Button></div></div>; })}</div>}</section></TabsContent>
    <TabsContent value="feedback"><section className="overflow-hidden border border-border bg-surface">{feedbackRows.length ? <div className="divide-y divide-border">{feedbackRows.map((row, index) => <div key={textValue(row.feedback_id, String(index))} className="grid grid-cols-[100px_minmax(0,1fr)_160px] gap-4 px-4 py-3 text-[13px]"><StatusBadge status={textValue(row.feedback, "pending")} label={textValue(row.feedback, "反馈")} /><div><p className="font-medium">{textValue(row.feedback_type, "一般反馈")}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{textValue(row.comment, textValue(row.feedback_text, "未提供说明"))}</p></div><span className="font-mono text-[10px] text-muted-foreground">{textValue(row.created_at)}</span></div>)}</div> : <EmptyState icon={MessageSquareWarning} compact title="没有用户反馈" description="对话中的好评、差评和纠错会出现在这里。" />}</section></TabsContent>
    <TabsContent value="analysis"><section className="overflow-hidden border border-border bg-surface">{analysisRows.length ? <div className="divide-y divide-border">{analysisRows.map((row, index) => <div key={textValue(row.feedback_id, String(index))} className="grid grid-cols-[minmax(0,1fr)_160px_100px] gap-4 px-4 py-3 text-[13px]"><div><p className="font-medium">{textValue(row.recommended_action, "待分析")}</p><p className="mt-1 text-xs text-muted-foreground">{textValue(row.reason, textValue(row.summary))}</p></div><span>{textValue(row.feedback_type)}</span><StatusBadge status={Boolean(row.needs_review) ? "needs_review" : "completed"} /></div>)}</div> : <EmptyState icon={MessageSquareWarning} compact title="没有反馈分析" description="后端完成反馈理解后会显示建议动作和审核状态。" />}</section></TabsContent>
    <TabsContent value="retrieval"><section className="overflow-hidden border border-border bg-surface">{retrievalRows.length ? <div className="divide-y divide-border">{retrievalRows.map((row, index) => <div key={textValue(row.feedback_id, String(index))} className="grid grid-cols-[minmax(0,1fr)_120px_120px] gap-4 px-4 py-3 text-[13px]"><div><p className="font-medium">{textValue(row.query, "检索反馈")}</p><p className="mt-1 text-xs text-muted-foreground">{textValue(row.reason, textValue(row.comment))}</p></div><Badge>{textValue(row.feedback_type, "weight")}</Badge><StatusBadge status={Boolean(row.enabled ?? true) ? "active" : "disabled"} /></div>)}</div> : <EmptyState icon={ScanSearch} compact title="没有检索调权反馈" description="需要调权的坏案例会沿用后端反馈流程进入这里。" />}</section></TabsContent>
  </Tabs></div></div>;
}
