[package]
name = "rust_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.0", features = ["extension-module"] }

rayon = "1.10"
sha2 = "0.10"
hex = "0.4"
jieba-rs = "0.10"
rust-stemmers = "1"
regex = "1"
unicode-casefold = "0.2"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
